"""initial migration

Revision ID: 4b223b85ff18
Revises: 9f3b62ea7df8
Create Date: 2022-04-19 10:10:03.555446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b223b85ff18'
down_revision = '9f3b62ea7df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('category', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
