"""Initial migration

Revision ID: 8da948219dc1
Revises: b6f18a40c712
Create Date: 2022-03-16 00:06:34.274535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da948219dc1'
down_revision = 'b6f18a40c712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_in_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invoice_nr', sa.String(length=100), nullable=False),
    sa.Column('customer', sa.String(length=100), nullable=False),
    sa.Column('job_name', sa.String(length=500), nullable=False),
    sa.Column('po_nr', sa.String(length=50), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('cogs', sa.Float(precision=20), nullable=False),
    sa.Column('cogs_account', sa.String(length=100), nullable=False),
    sa.Column('invoiced', sa.Boolean(), nullable=True),
    sa.Column('month_invoiced', sa.String(length=50), nullable=True),
    sa.Column('product_at_co', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_nr'),
    sa.UniqueConstraint('po_nr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_in_process')
    # ### end Alembic commands ###
