"""Initial migration

Revision ID: a99552f8c345
Revises: e49968ba459d
Create Date: 2022-03-29 20:12:35.410435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99552f8c345'
down_revision = 'e49968ba459d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_voucher',
    sa.Column('vendor_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('voucher_year', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('voucher_month', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('cogs', sa.Float(precision=50), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('vendor_id', 'voucher_year', 'voucher_month')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general_voucher')
    # ### end Alembic commands ###
