"""Initial migration

Revision ID: b6f18a40c712
Revises: e1820dd9562b
Create Date: 2022-03-15 23:57:27.715271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6f18a40c712'
down_revision = 'e1820dd9562b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_in_process', sa.Column('product_at_co', sa.Boolean(), nullable=True))
    op.drop_column('work_in_process', 'prouct_at_co')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_in_process', sa.Column('prouct_at_co', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('work_in_process', 'product_at_co')
    # ### end Alembic commands ###
