"""Initial migration

Revision ID: e49968ba459d
Revises: 6890ce5203cb
Create Date: 2022-03-29 18:11:01.244636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49968ba459d'
down_revision = '6890ce5203cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('account_nr', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_nr')
    )
    op.create_table('work_in_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invoice_nr', sa.String(length=100), nullable=False),
    sa.Column('customer', sa.String(length=100), nullable=False),
    sa.Column('job_name', sa.String(length=500), nullable=False),
    sa.Column('po_nr', sa.String(length=50), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('cogs', sa.Float(precision=50), nullable=False),
    sa.Column('cogs_account', sa.String(length=500), nullable=False),
    sa.Column('invoiced', sa.String(length=5), nullable=False),
    sa.Column('month_invoiced', sa.String(length=50), nullable=True),
    sa.Column('product_at_co', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_nr'),
    sa.UniqueConstraint('po_nr')
    )
    op.create_table('general_voucher',
    sa.Column('voucher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher_row_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('voucher_year', sa.String(length=100), nullable=False),
    sa.Column('voucher_month', sa.String(length=100), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('cogs', sa.Float(precision=50), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('voucher_id', 'voucher_row_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general_voucher')
    op.drop_table('work_in_process')
    op.drop_table('account')
    # ### end Alembic commands ###
